version: '3'

services:
  dev:
    build:
      context: .
    env_file:
      - .env.development
    ports:
      - 3000:3000
    command: yarn dev
    volumes:
      - ".:/app"
  test:
    build:
      context: .
    env_file:
      - .env.test
    environment:
      - CI=true
    command: yarn test
